### PR TITLE
add match service name with version in filter

### PR DESCRIPTION
**Pull request by intech**
Close issue #39

### CODE REVIEW

**Comment by intech** [comment]
One moment, this broken

**Comment by icebob** [comment]
It's not so easy :P
If the version is a `Number` you should prefix with `v`. 

By the way, as for 0.14, there is a `fullName` property of services.

**Comment by icebob** [comment]
Similar code: https://github.com/moleculerjs/moleculer/blob/master/src/service.js#L83

**Comment by intech** [comment]
> Similar code: https://github.com/moleculerjs/moleculer/blob/master/src/service.js#L83
Pass to fullName will not breaking change?

**Comment by icebob** [comment]
Yes, so would be good to check `service.fullName != null ? service.fullName : (......)`

**Comment by icebob** [comment]
Could you try it? I've just write here on Github, I don't know it doesn't contain some syntax error.

**Comment by intech** [comment]
https://repl.it/@IvanZhuravlev/moleculer-createService
all ok!
Снимок экрана от 2019-12-13 00-40-00

**Pull request merged**
