### PR TITLE
Complete rewrite of REPL

### LINKED ISSUE #12: is there a way to subscribe an event?

### LINKED ISSUE #47: Hexadecimal is converted into number in action parameter
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Current Behavior

We have an action with the following parameter setup:

```
params: {
  transactionHash: 'string'
}
```

We pass a hexadecimal string, eg. '0xab706...' into the params, the hexadecimal string is being converted into number '7.7544153918976e+76'.

## Expected Behavior

Expected to pass the original hexadecimal string and not convert it.

### Context

* Moleculer version:  ^0.13.0
* NodeJS version: 10.16.0
* Operating System: MacOS Catalina

### LINKED ISSUE #48: Dropping Vorpal and Migrating to Shargs
@Yord yesterday [I've started to play](https://github.com/AndreMaz/moleculer-repl/tree/shargs) with `shargs-repl`. I've managed to implement some basic commands (e.g., `cls`, `exit`, etc.) but I need some guidance on the [`call`](https://github.com/AndreMaz/moleculer-repl/blob/shargs/src/commands/shargs/call.js) command. If possible, I want `args` to have the same structure as vorpal's `args`

Here's how my implementation looks like:
```js
const subCommandOpt = subcommand([
    stringPos('actionName', { desc: "Action name (e.g., greeter.hello)", descArg: 'actionName', required: true} ),
    stringPos('jsonParams', { desc: `JSON Parameters (e.g. '{"a": 5}' )`, descArg: 'jsonParams'} ),
    stringPos('meta', { desc: "Metadata to pass to the service action. Must start with '#' (e.g., --#auth 123)", descArg: 'meta'} ),
    string("load", ["--load"], { desc: "Load params from file.", descArg: 'filename' }),
    string("stream", ["--stream"], { desc: "Save response to file.", descArg: 'filename' }),
    string("save", ["--save"], { desc: "Save response to file.", descArg: 'filename' }),
]);
```

and this is vopral implementation:
```js
vorpal
	.removeIfExist("call")
	.command("call <actionName> [jsonParams] [meta]", "Call an action")
	.autocomplete({
		data() {
			return _.uniq(_.compact(broker.registry.getActionList({}).map(item => item && item.action ? item.action.name: null)));
		}
	})
	.option("--load [filename]", "Load params from file")
	.option("--stream [filename]", "Send a file as stream")
	.option("--save [filename]", "Save response to file")
	.allowUnknownOptions()
	.action((args, done) => call(broker, args, done));
```

and below are some examples of how `vorpal` and `shargs` parse the input data:
___
1. Call with `--load` option.

**Command**
```
call greeter.data --load ./package.json --save p.json
```
**vorpal args**
```js
{
  options: { load: './package.json', save: 'p.json' },
  actionName: 'greeter.data',
  rawCommand: 'call greeter.data --load ./package.json --save p.json'
}
```
**shargs args**
```js
{
  _: [],
  actionName: 'greeter.data',
  load: './package.json',
  save: 'p.json'
}
```
___

2. call with JSON string

**Command**
```
call greeter.data '{"a": 5, "b": "Bob", "c": true, "d": false, "e": { "f": "hello" } }'
```
**vorpal args**
```js
{
  options: {},
  actionName: 'greeter.data',
  jsonParams: '{"a": 5, "b": "Bob", "c": true, "d": false, "e": { "f": "hello" } }',
  rawCommand: `call greeter.data '{"a": 5, "b": "Bob", "c": true, "d": false, "e": { "f": "hello" } }'`
}
```

**shargs args**
```js
{
  _: [],
  actionName: 'greeter.data',
  jsonParams: '{"a": 5, "b": "Bob", "c": true, "d": false, "e": { "f": "hello" } }'
}
```
___

3. Call with random params

**Command**
```
call greeter.data --a 5 --b Bob --c --no-d --e.f "hello"
```
**vorpal args**
```js
{
  options: { a: 5, b: 'Bob', c: true, d: false, e: { f: 'hello' } },
  actionName: 'greeter.data',
  rawCommand: 'call greeter.data --a 5 --b Bob --c --no-d --e.f "hello"'
}
```
**shargs args**
```js
{
  _: [ '--b', 'Bob', '--c', '--no-d', '--e.f', 'hello' ],
  actionName: 'greeter.data',
  jsonParams: '--a',
  meta: '5'
}
```

With a little work 1. and 2. can be transformed into the desired shape but the 3. is completely wrong.
What's is the correct way of parsing unknown params? Vorpal has a function called `.allowUnknownOptions()` that parses unknown options that start with `--` (e.g. `--something 1`) into 
```js
{
  options: { something: 1 },
  actionName: 'greeter.data',
  rawCommand: 'call greeter.data --something 1'
}
```

How can I achieve the same behavior with `shargs`?

### LINKED ISSUE #54: Parameters not passed as string
```
mol $ call user.create --phone "+1111111" --passcode "0033"
>> Call 'user.create' with params: { phone: 1111111, passcode: 33 }
```

however, when passing as json it works.
```
mol $ call user.create '{"phone": "+ 1111111", "passcode": "0033"}'
>> Call 'user.create' with params: { phone: '+ 1111111', passcode: '0033' }
```

### LINKED ISSUE #55: feat: add options for `call`, `emit`, `broadcast`
Provide the ability to transfer not only `meta` but also other call options

### LINKED ISSUE #56: CVE advisory on dependencies
```
λ npm audit
# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix --force`
Will install moleculer-repl@0.5.7, which is a breaking change
node_modules/@moleculer/vorpal/node_modules/ansi-regex
node_modules/inquirer/node_modules/ansi-regex
node_modules/log-update/node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/@moleculer/vorpal/node_modules/strip-ansi
  node_modules/inquirer/node_modules/strip-ansi
  node_modules/log-update/node_modules/strip-ansi
    @moleculer/vorpal  *
    Depends on vulnerable versions of strip-ansi
    node_modules/@moleculer/vorpal
      moleculer-repl  >=0.6.0
      Depends on vulnerable versions of @moleculer/vorpal
      node_modules/moleculer-repl
    inquirer  3.2.0 - 7.0.4
    Depends on vulnerable versions of strip-ansi
    node_modules/inquirer
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/log-update/node_modules/string-width
      wrap-ansi  3.0.0 - 6.1.0
      Depends on vulnerable versions of string-width
      Depends on vulnerable versions of strip-ansi
      node_modules/log-update/node_modules/wrap-ansi
        log-update  2.1.0 - 3.4.0
        Depends on vulnerable versions of wrap-ansi
        node_modules/log-update
```

Looks like some dependencies in `@moleculerjs/vorpal` are causing the issues.

### PR DESCRIPTION
**Pull request by AndreMaz**
This PR rewrites REPL terminal in a way that it no longer depends on vorpal, which is an old and outdated lib.
It uses native REPL + [commander.js](https://github.com/tj/commander.js/) (for commands) + [yargs-parser](https://github.com/yargs/yargs-parser#readme) (for args parsing).

Despite being a complete rewrite it should behave exactly as the old (vorpal-based) REPL

Things that this PR will solve:
Fixes #56 
Closes #48 
Fixes #54 (see https://github.com/AndreMaz/moleculer-repl/blob/4bfbee40f2d556dca05265524ddd6890570b233b/test/call.spec.js#L80-L95)
Fixes #47 (see https://github.com/AndreMaz/moleculer-repl/blob/d2c1e8742cb5964650a3cbbcfbb5f89833bcd764/test/call.spec.js#L98-L120)
Closes #55 
Closes #12

### CODE REVIEW

**Comment by ujwal-setlur** [comment]
So, now ``repl.exec('some-command')`` does not work anymore. I use it to programmatically quit from the repl console:
```
 repl.exec('quit');
```
I guess that was a ``vorpal`` command. What would be the equivalent?

**Comment by ujwal-setlur** [comment]
Also, the typings have to be updated in ``index.d.ts`` of ``moleculer``

**Comment by AndreMaz** [comment]
@ujwal-setlur to quit you can use 
```js
repl.eval("quit");
```

**Comment by ujwal-setlur** [comment]
@AndreMaz Thanks!

**Pull request merged**
